### ISSUE TITLE
Pradakshinam Android Hybrid app

### ISSUE THREAD

**Issue by obidostech** [madewithangular/madewithangular.github.io#140]
Hi, we have created an Android app Pradakshinam that uses Angular JS. Can apps be listed in this site?
https://play.google.com/store/apps/details?id=com.obidostech.pradakshinam

**Comment by lpolepeddi** [comment]
Thanks @obidostech! At the moment we don't list mobile apps, but I'll keep this issue open in case that changes.

**Comment by obidostech** [comment]
Thanks @lpolepeddi.

**Comment by lalithpolepeddi** [comment]
Thanks again for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing your project here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
