### ISSUE TITLE
Could you add https://rocketbots.io/ to your post.

### ISSUE THREAD

**Issue by westu93** [madewithangular/madewithangular.github.io#291]
Hi,
Wondering if you could please add https://rocketbots.io/ to your website https://www.madewithangular.com. 

Thank you :)

**Comment by westu93** [comment]
https://docs.rocketbots.io/

**Comment by lpolepeddi** [comment]
Thanks for sharing. Where do you see Angular being used on this site?

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We're in the middle of a little spring cleaning on our [new website](https://www.madewithangular.com) and this GitHub repo, aiming to tidy up our open issues. In reviewing our open issues, we noticed that https://rocketbots.io/ has evolved away from using Angular. Given these changes, we'll go ahead and close this issue for the time being. If you have any new projects made with Angular, please consider [sharing them in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432)! The discussion is a better fit because it provides an opportunity for the community to see, appreciate, and discuss your work - thank you!
