### ISSUE TITLE
RotaCloud

### ISSUE THREAD

**Issue by david-brandon** [madewithangular/madewithangular.github.io#312]
RotaCloud (rotacloud.com) built using Angular 7.1.4

**Comment by lpolepeddi** [comment]
Could you send a 1280x711 screenshot of the app after someone logs in?

**Comment by david-brandon** [comment]
@lpolepeddi certainly, here is a link to a screenshot... https://s3-eu-west-1.amazonaws.com/rotacloud-website/rotacloud-screenshot.png

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We're in the middle of a little spring cleaning on our [new website](https://www.madewithangular.com) and this GitHub repo, aiming to tidy up our open issues. In reviewing our open issues, we noticed that https://rotacloud.com/ has evolved away from using Angular. Given these changes, we'll go ahead and close this issue for the time being. If you have any new projects made with Angular, please consider [sharing them in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432)! The discussion is a better fit because it provides an opportunity for the community to see, appreciate, and discuss your work - thank you!
