### ISSUE TITLE
https://www.xilo.io

### ISSUE THREAD

**Issue by ArjunBollam** [madewithangular/madewithangular.github.io#320]
Xilo an online insurance quote company made with Angular 7. https://www.xilo.io

**Comment by lpolepeddi** [comment]
Could you send a 1280x711 screenshot of the app after someone logs in?

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We're in the middle of a little spring cleaning on our [new website](https://www.madewithangular.com) and this GitHub repo, aiming to tidy up our open issues. In reviewing our open issues, we noticed that https://www.xilo.io/ has evolved away from using Angular. Given these changes, we'll go ahead and close this issue for the time being. If you have any new projects made with Angular, please consider [sharing them in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432)! The discussion is a better fit because it provides an opportunity for the community to see, appreciate, and discuss your work - thank you!
