### ISSUE TITLE
https://api.amexio.org/api/v5.9/index.html#/getting-started

### ISSUE THREAD

**Issue by ArjunBollam** [madewithangular/madewithangular.github.io#325]
Amexio uses Angular 7  https://api.amexio.org/api/v5.9/index.html#/getting-started

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We're in the middle of a little spring cleaning on our [new website](https://www.madewithangular.com) and this GitHub repo, aiming to tidy up our open issues. In reviewing our open issues, we noticed that your project is no longer available online. Given these changes, we'll go ahead and close this issue for the time being. If you have any new projects made with Angular, please consider [sharing them in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432)! The discussion is a better fit because it provides an opportunity for the community to see, appreciate, and discuss your work - thank you!
