### ISSUE TITLE
Add site https://emploreo.com

### ISSUE THREAD

**Issue by kchumichkin** [madewithangular/madewithangular.github.io#326]
Category: Finance
emploreo.com - Job Posting Board based in Poland
made with Angular 7 + Angular Material
desktop and mobile friendly

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing your project here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
