### ISSUE TITLE
Web mail https://ej2.syncfusion.com/showcase/angular/webmail/

### ISSUE THREAD

**Issue by suresh-mohan** [madewithangular/madewithangular.github.io#327]
It was developed using Angular 5

https://ej2.syncfusion.com/showcase/angular/webmail/

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing your project here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
