### ISSUE TITLE
Add https://www.medolubov.ru

### ISSUE THREAD

**Issue by Dok11** [madewithangular/madewithangular.github.io#333]
URL: https://www.medolubov.ru/en
Version: 4.4.6
Category: Food & Drink

![ng-medolubov-4 4 6](https://user-images.githubusercontent.com/2697890/57710090-e8786900-7674-11e9-9722-4d408d03ccd9.jpg)

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing your project here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
