### ISSUE TITLE
Add http://ogprim.ru

### ISSUE THREAD

**Issue by Dok11** [madewithangular/madewithangular.github.io#334]
URL: http://ogprim.ru/en
Version: 5.2.9
Category: Education

![ng-ogprim-5 2 9](https://user-images.githubusercontent.com/2697890/57710138-0219b080-7675-11e9-8571-e60f4446e5e6.jpg)

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We're in the middle of a little spring cleaning on our [new website](https://www.madewithangular.com) and this GitHub repo, aiming to tidy up our open issues. In reviewing our open issues, we were unable to load your project. We'll go ahead and close this issue for the time being. If you have any new projects made with Angular, please consider [sharing them in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432)! The discussion is a better fit because it provides an opportunity for the community to see, appreciate, and discuss your work - thank you!
