### ISSUE TITLE
Add https://bixbeat.com - Music site/app

### ISSUE THREAD

**Issue by tomgruszowski** [madewithangular/madewithangular.github.io#347]
Category: Entertainment
Website: bixbeat.com - Music Portal
Version: Angular (7.2.15 - soon to be 8, Material + Bootstrap.
Desktop and Mobile, also embedded in App Store apps for iOS and Android
![Capture](https://user-images.githubusercontent.com/1247564/60037175-171f3180-966e-11e9-9671-522bf68d9bbd.PNG)
![Capture2](https://user-images.githubusercontent.com/1247564/60037246-4897fd00-966e-11e9-8fbb-259f352c47ba.PNG)

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing your project here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
