### ISSUE TITLE
Add thehashad.com made with angular 

### ISSUE THREAD

**Issue by ramkumar196** [madewithangular/madewithangular.github.io#349]
Category: Classified 
Website: http://thehashad.com
made with Angular + Bootstrap
desktop and mobile friendly

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We're in the middle of a little spring cleaning on our [new website](https://www.madewithangular.com) and this GitHub repo, aiming to tidy up our open issues. In reviewing our open issues, we noticed that your project is no longer available online. We'll go ahead and close this issue for the time being. If you have any new projects made with Angular, please consider [sharing them in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432)! The discussion is a better fit because it provides an opportunity for the community to see, appreciate, and discuss your work - thank you!
