### ISSUE TITLE
https://apply.commonapp.org

### ISSUE THREAD

**Issue by VamsiDharmaji** [madewithangular/madewithangular.github.io#359]
Add this site
Version : 7

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing https://apply.commonapp.org here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
