### ISSUE TITLE
Site Suggestion: DealCheck.io - Leading Property Analysis App

### ISSUE THREAD

**Issue by netus01** [madewithangular/madewithangular.github.io#365]
DealCheck.io is the leading property analysis app with over 100,000 users in North America. It's used by real estate investors, agents and entrepreneurs to analyze investment properties, perform financial projections and find the best real estate deals.

Website: https://dealcheck.io/
App: https://app.dealcheck.io/
Technologies: AngularJS, Bootstrap

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing https://app.dealcheck.io/ here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
