### ISSUE TITLE
site suggestion: Bricks

### ISSUE THREAD

**Issue by sinsunsan** [madewithangular/madewithangular.github.io#368]
Bricks is the agile collaborative app for Architecture & Construction. It allows architecture professionals to collaborate efficiently, plan the work to be done, assign tasks and use agile Methods for coordination.

Website: https://www.bricksapp.io/
App: https://app.bricksapp.io/
Technologies: Angular8, Ngrx, Material, Node...

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing https://app.bricksapp.io/ here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
