### ISSUE TITLE
Site Suggestion: https://www.cidadessustentaveis.org.br

### ISSUE THREAD

**Issue by geovannyAvelar** [madewithangular/madewithangular.github.io#375]
Well, it's on beta phase yet, but it's a good example. Made with Angular 7. 

Programa Cidades Sustentáveis (Sustainable Cities Program).

The Sustainable Cities Program (SCP) is an urban sustainability agenda that incorporates the social, environmental, economic, political and cultural in municipal planning. 

https://www.cidadessustentaveis.org.br

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing your project here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
