### ISSUE TITLE
Site Suggestion - http://daniboomerang.com/

### ISSUE THREAD

**Issue by daniboomerang** [madewithangular/madewithangular.github.io#383]
http://daniboomerang.com/

I created this site in 2016 using Angular 1.2.
Even if it's really out of date I still enjoy pretty much to scroll through this amazing 3-layer-parallax of animated SVGs!

I thought...It might be a nice thing to see the power of the old Angular 1.X FRW!

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing your project here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
