### ISSUE TITLE
Site Suggestion - https://app.petsitterdashboard.com/

### ISSUE THREAD

**Issue by ConsultDarryl** [madewithangular/madewithangular.github.io#384]
https://app.petsitterdashboard.com

Pet Sitter Dashboard is the #1 free platform for professional Dog Walkers & Pet Sitters who need a quick and easy way to manage their business.

Find out more at https://petsitterdashboard.com/

- Appointment scheduling
- Invoices and payment tracking
- Customer and pet database
- Business finances
- Reporting
- GBP, EUR and USD
- Easy to import your existing customers
- Works offline

Pet Sitter Dashboard is everything you need to run a successful pet sitting business.

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing https://app.petsitterdashboard.com/ here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
