### ISSUE TITLE
Site Suggestion : http://13.229.70.212:8168/disney-heroes/

### ISSUE THREAD

**Issue by erickyi2006** [madewithangular/madewithangular.github.io#391]
A website where players of Disney Heroes: Battle mode can analyze the heroes to form his /her team

![image](https://user-images.githubusercontent.com/19684107/92290280-f2ebff80-ef56-11ea-9a85-6f85d8aed9c8.png)

- It shows the heroes with fun facts in an interactive world map 
- The app also shows several, popular statistics and  charts
- It allows the player to choose the friendship disk 
- It shows popular team combinations 
 
As a side, the app showcases several angular challenges namely

- Dynamic Components
- Router navigation for out of zone
- Redesigned using a common symbolic node_modules
- Fixed initialising of component that depends on the completion of data loading in a service
- Fixed resource loading in production build with aot=true
- Customized a readonly mat-slider
- Customized tooltips without using ViewEncapsulation

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We're in the middle of a little spring cleaning on our [new website](https://www.madewithangular.com) and this GitHub repo, aiming to tidy up our open issues. In reviewing our open issues, we were unable to load your project. We'll go ahead and close this issue for the time being. If you have any new projects made with Angular, please consider [sharing them in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432)! The discussion is a better fit because it provides an opportunity for the community to see, appreciate, and discuss your work - thank you!
