### ISSUE TITLE
Site Suggestions - https://meetinchat.com

### ISSUE THREAD

**Issue by iwxmedia** [madewithangular/madewithangular.github.io#392]
Adult Chat website
Category: Entertainment

About 5000 sessions per day with an average session duration of 25 mins.
The stats linked to Google Analytics can be browsed on [SimilarWeb](https://www.similarweb.com/website/meetinchat.com/)

Actual Version (Sep 2020): Angular Universal 7.2.13
Backend: ASP.NET Core + Entity Framework + SQL Server

By the end of 2020 it will migrate to Angular Universal 10 using improving the load performance using the TransferState 

The actual solution is composed by about 160 components and 40 services.
In the adult industry it seems nobody is using angular.

Main features
- Account management
- Real time chat (Using SignalR)
- Social management (friendship, private messages)
- Blog section
- Complex advertisement management
- Admin section
- Cam 2 Cam feature (using RTCMultiConnection)
- Internal search engine
- Multilingual (ngx-translate)

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing your project here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
