### ISSUE TITLE
Site Suggestion: https://whereiveflown.com

### ISSUE THREAD

**Issue by sebastiaanh** [madewithangular/madewithangular.github.io#394]
**Where I've Flown**: Easily create your own 3D map of all flights you’ve ever taken, and share the URL with anyone you want. Similar to "where I've been" maps. No registration needed. 

Angular 10.1.4, fully clientside, PWA.

**Comment by sebastiaanh** [comment]
Preview 1280x711
![thumb](https://user-images.githubusercontent.com/73762410/97791699-85b2be80-1bd5-11eb-82a0-1d226734c0ff.jpg)

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing your project here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
