### ISSUE TITLE
CRM APP Suggestion crm.pipelinersales.com

### ISSUE THREAD

**Issue by rBull** [madewithangular/madewithangular.github.io#400]
Pipeliner CRM (one of the best CRM according to G2 Crowd - https://www.g2.com/categories/crm ) is built with Angular.

https://crm.pipelinersales.com
more info https://www.pipelinersales.com

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We recently [revamped our website](https://www.madewithangular.com) to improve the showcase and made some significant changes to this GitHub repository to improve collaboration. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing https://crm.pipelinersales.com/ here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
