### ISSUE TITLE
Pharmaceutical Labeling Software, Regulatory Labeling Management

### ISSUE THREAD

**Issue by freyrsolutions** [madewithangular/madewithangular.github.io#416]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mkaram/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mkaram/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Freyr   label 360 is a [Pharmaceutical Labeling Software](
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mkaram/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mkaram/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

https://www.freyrlabel.com/
--

</body>

</html>
) that Supports End to End   Label Management, Label Tracking and Deviation Management for Pharmaceutical   Companies across the Globe.
--

</body>

</html>

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We're in the middle of a little spring cleaning on our [new website](https://www.madewithangular.com) and this GitHub repo, aiming to tidy up our open issues. In reviewing our open issues, we noticed that https://www.freyrlabel.com/ is no longer available online. We'll go ahead and close this issue for the time being. If you have any new projects made with Angular, please consider [sharing them in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432)! The discussion is a better fit because it provides an opportunity for the community to see, appreciate, and discuss your work - thank you!
