### ISSUE TITLE
Structured Product Labeling, Structure Product Monograph Software

### ISSUE THREAD

**Issue by freyrsolutions** [madewithangular/madewithangular.github.io#417]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mkaram/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mkaram/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Freyr   SPL/SPM is cloud hosted and On-premise software that supports in electronic   Pharma registration &amp; listing management, Labeling Management, PI   submission in[ SPL/SPM Format](
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mkaram/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mkaram/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

https://www.freyrsplspm.com/
--

</body>

</html>
) with Automated notification updates.
--

</body>

</html>

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! We're in the middle of a little spring cleaning on our [new website](https://www.madewithangular.com) and this GitHub repo, aiming to tidy up our open issues. In reviewing our open issues, we noticed that https://www.freyrsplspm.com/ has evolved away from using Angular. Given these changes, we'll go ahead and close this issue for the time being. If you have any new projects made with Angular, please consider [sharing them in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432)! The discussion is a better fit because it provides an opportunity for the community to see, appreciate, and discuss your work - thank you!
