### ISSUE TITLE
Sites Suggestion - AI and CRM

### ISSUE THREAD

**Issue by clientelacrm** [madewithangular/madewithangular.github.io#430]
bard.google.com
app.clientelacrm.com

**Comment by lalithpolepeddi** [comment]
Nice find! We've added https://gemini.google.com/ to the showcase on our [new website](https://www.madewithangular.com).

We're in the middle of a little spring cleaning on this GitHub repo. As part of these updates, we're moving conversations around projects made with Angular [to this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - please consider sharing app.clientelacrm.com here! The discussion is a better fit because provides an opportunity for the community to see, appreciate, and ask questions about your work. In light of these updates, we're closing this issue and hope to see you in our new and improved space - thank you!
